// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// softmax_arma
arma::vec softmax_arma(const arma::vec& x);
RcppExport SEXP _RSiena_softmax_arma(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(softmax_arma(x));
    return rcpp_result_gen;
END_RCPP
}
// softmax_arma_by_group
arma::vec softmax_arma_by_group(const arma::vec& x, const arma::ivec& group);
RcppExport SEXP _RSiena_softmax_arma_by_group(SEXP xSEXP, SEXP groupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type group(groupSEXP);
    rcpp_result_gen = Rcpp::wrap(softmax_arma_by_group(x, group));
    return rcpp_result_gen;
END_RCPP
}
// softmax_rcpp_grouped
arma::vec softmax_rcpp_grouped(const arma::vec& x, const arma::ivec& g1, const arma::ivec& g2, const arma::ivec& g3);
RcppExport SEXP _RSiena_softmax_rcpp_grouped(SEXP xSEXP, SEXP g1SEXP, SEXP g2SEXP, SEXP g3SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type g1(g1SEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type g2(g2SEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type g3(g3SEXP);
    rcpp_result_gen = Rcpp::wrap(softmax_rcpp_grouped(x, g1, g2, g3));
    return rcpp_result_gen;
END_RCPP
}
// softmax_rcpp_grouped_mat
arma::vec softmax_rcpp_grouped_mat(const arma::vec& x, const arma::imat& G);
RcppExport SEXP _RSiena_softmax_rcpp_grouped_mat(SEXP xSEXP, SEXP GSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::imat& >::type G(GSEXP);
    rcpp_result_gen = Rcpp::wrap(softmax_rcpp_grouped_mat(x, G));
    return rcpp_result_gen;
END_RCPP
}
// softmax_rcpp_grouped_lst
arma::vec softmax_rcpp_grouped_lst(const arma::vec& x, const Rcpp::List& G);
RcppExport SEXP _RSiena_softmax_rcpp_grouped_lst(SEXP xSEXP, SEXP GSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type G(GSEXP);
    rcpp_result_gen = Rcpp::wrap(softmax_rcpp_grouped_lst(x, G));
    return rcpp_result_gen;
END_RCPP
}
// softmax_rcpp_grouped_cols
arma::vec softmax_rcpp_grouped_cols(const Rcpp::DataFrame& data, const std::string& val_col, const Rcpp::CharacterVector& group_cols);
RcppExport SEXP _RSiena_softmax_rcpp_grouped_cols(SEXP dataSEXP, SEXP val_colSEXP, SEXP group_colsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type val_col(val_colSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type group_cols(group_colsSEXP);
    rcpp_result_gen = Rcpp::wrap(softmax_rcpp_grouped_cols(data, val_col, group_cols));
    return rcpp_result_gen;
END_RCPP
}
// grouped_agg_cpp
Rcpp::List grouped_agg_cpp(const Rcpp::NumericVector& x, const Rcpp::IntegerMatrix& G, bool na_rm, bool do_mean);
RcppExport SEXP _RSiena_grouped_agg_cpp(SEXP xSEXP, SEXP GSEXP, SEXP na_rmSEXP, SEXP do_meanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type G(GSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    Rcpp::traits::input_parameter< bool >::type do_mean(do_meanSEXP);
    rcpp_result_gen = Rcpp::wrap(grouped_agg_cpp(x, G, na_rm, do_mean));
    return rcpp_result_gen;
END_RCPP
}
// loo_change_probs
arma::mat loo_change_probs(const arma::mat& contribMat, const arma::vec& theta, const arma::ivec& group_id);
RcppExport SEXP _RSiena_loo_change_probs(SEXP contribMatSEXP, SEXP thetaSEXP, SEXP group_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type contribMat(contribMatSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type group_id(group_idSEXP);
    rcpp_result_gen = Rcpp::wrap(loo_change_probs(contribMat, theta, group_id));
    return rcpp_result_gen;
END_RCPP
}
// l1d_grouped
arma::mat l1d_grouped(const arma::vec& ref, const arma::mat& loo, const arma::ivec& group_id);
RcppExport SEXP _RSiena_l1d_grouped(SEXP refSEXP, SEXP looSEXP, SEXP group_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type ref(refSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type loo(looSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type group_id(group_idSEXP);
    rcpp_result_gen = Rcpp::wrap(l1d_grouped(ref, loo, group_id));
    return rcpp_result_gen;
END_RCPP
}
// kld_grouped
arma::mat kld_grouped(const arma::vec& ref, const arma::mat& loo, const arma::ivec& group_id);
RcppExport SEXP _RSiena_kld_grouped(SEXP refSEXP, SEXP looSEXP, SEXP group_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type ref(refSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type loo(looSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type group_id(group_idSEXP);
    rcpp_result_gen = Rcpp::wrap(kld_grouped(ref, loo, group_id));
    return rcpp_result_gen;
END_RCPP
}
// mlogit_update
arma::vec mlogit_update(const arma::vec& p, const arma::vec& delta_u, const arma::ivec& group_id, int perturbType);
RcppExport SEXP _RSiena_mlogit_update(SEXP pSEXP, SEXP delta_uSEXP, SEXP group_idSEXP, SEXP perturbTypeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type p(pSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta_u(delta_uSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type group_id(group_idSEXP);
    Rcpp::traits::input_parameter< int >::type perturbType(perturbTypeSEXP);
    rcpp_result_gen = Rcpp::wrap(mlogit_update(p, delta_u, group_id, perturbType));
    return rcpp_result_gen;
END_RCPP
}
