// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// softmax_rcpp_by_group
Rcpp::NumericVector softmax_rcpp_by_group(const Rcpp::NumericVector& x, const Rcpp::IntegerVector& group);
RcppExport SEXP _RSiena_softmax_rcpp_by_group(SEXP xSEXP, SEXP groupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type group(groupSEXP);
    rcpp_result_gen = Rcpp::wrap(softmax_rcpp_by_group(x, group));
    return rcpp_result_gen;
END_RCPP
}
// grouped_agg_cpp
Rcpp::List grouped_agg_cpp(const Rcpp::NumericVector& x, const Rcpp::IntegerMatrix& G, bool na_rm, bool do_mean);
RcppExport SEXP _RSiena_grouped_agg_cpp(SEXP xSEXP, SEXP GSEXP, SEXP na_rmSEXP, SEXP do_meanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type G(GSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    Rcpp::traits::input_parameter< bool >::type do_mean(do_meanSEXP);
    rcpp_result_gen = Rcpp::wrap(grouped_agg_cpp(x, G, na_rm, do_mean));
    return rcpp_result_gen;
END_RCPP
}
// build_scatter_idx
Rcpp::IntegerVector build_scatter_idx(const Rcpp::IntegerMatrix& G_sorted, const Rcpp::IntegerVector& ord);
RcppExport SEXP _RSiena_build_scatter_idx(SEXP G_sortedSEXP, SEXP ordSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type G_sorted(G_sortedSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type ord(ordSEXP);
    rcpp_result_gen = Rcpp::wrap(build_scatter_idx(G_sorted, ord));
    return rcpp_result_gen;
END_RCPP
}
// scatter_agg_1d
Rcpp::List scatter_agg_1d(const Rcpp::NumericVector& vals, const Rcpp::IntegerVector& row_group, int nGroups, bool na_rm);
RcppExport SEXP _RSiena_scatter_agg_1d(SEXP valsSEXP, SEXP row_groupSEXP, SEXP nGroupsSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type vals(valsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type row_group(row_groupSEXP);
    Rcpp::traits::input_parameter< int >::type nGroups(nGroupsSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    rcpp_result_gen = Rcpp::wrap(scatter_agg_1d(vals, row_group, nGroups, na_rm));
    return rcpp_result_gen;
END_RCPP
}
// grouped_agg_matrix_cpp
Rcpp::List grouped_agg_matrix_cpp(const Rcpp::NumericMatrix& X, const Rcpp::IntegerMatrix& G, bool na_rm, bool do_mean);
RcppExport SEXP _RSiena_grouped_agg_matrix_cpp(SEXP XSEXP, SEXP GSEXP, SEXP na_rmSEXP, SEXP do_meanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type G(GSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    Rcpp::traits::input_parameter< bool >::type do_mean(do_meanSEXP);
    rcpp_result_gen = Rcpp::wrap(grouped_agg_matrix_cpp(X, G, na_rm, do_mean));
    return rcpp_result_gen;
END_RCPP
}
// grouped_agg_from_cols
Rcpp::List grouped_agg_from_cols(const Rcpp::NumericVector& x, const Rcpp::List& group_cols, bool na_rm, bool do_mean);
RcppExport SEXP _RSiena_grouped_agg_from_cols(SEXP xSEXP, SEXP group_colsSEXP, SEXP na_rmSEXP, SEXP do_meanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type group_cols(group_colsSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    Rcpp::traits::input_parameter< bool >::type do_mean(do_meanSEXP);
    rcpp_result_gen = Rcpp::wrap(grouped_agg_from_cols(x, group_cols, na_rm, do_mean));
    return rcpp_result_gen;
END_RCPP
}
// loo_change_probs
Rcpp::NumericMatrix loo_change_probs(const Rcpp::NumericMatrix& contribMat, const Rcpp::NumericVector& theta, const Rcpp::IntegerVector& group_id);
RcppExport SEXP _RSiena_loo_change_probs(SEXP contribMatSEXP, SEXP thetaSEXP, SEXP group_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type contribMat(contribMatSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type group_id(group_idSEXP);
    rcpp_result_gen = Rcpp::wrap(loo_change_probs(contribMat, theta, group_id));
    return rcpp_result_gen;
END_RCPP
}
// l1d_grouped
Rcpp::NumericMatrix l1d_grouped(const Rcpp::NumericVector& ref, const Rcpp::NumericMatrix& loo, const Rcpp::IntegerVector& group_id);
RcppExport SEXP _RSiena_l1d_grouped(SEXP refSEXP, SEXP looSEXP, SEXP group_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type ref(refSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type loo(looSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type group_id(group_idSEXP);
    rcpp_result_gen = Rcpp::wrap(l1d_grouped(ref, loo, group_id));
    return rcpp_result_gen;
END_RCPP
}
// kld_grouped
Rcpp::NumericMatrix kld_grouped(const Rcpp::NumericVector& ref, const Rcpp::NumericMatrix& loo, const Rcpp::IntegerVector& group_id);
RcppExport SEXP _RSiena_kld_grouped(SEXP refSEXP, SEXP looSEXP, SEXP group_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type ref(refSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type loo(looSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type group_id(group_idSEXP);
    rcpp_result_gen = Rcpp::wrap(kld_grouped(ref, loo, group_id));
    return rcpp_result_gen;
END_RCPP
}
// mlogit_update
Rcpp::NumericVector mlogit_update(const Rcpp::NumericVector& p, const Rcpp::NumericVector& delta_u, const Rcpp::IntegerVector& group_id, int perturbType);
RcppExport SEXP _RSiena_mlogit_update(SEXP pSEXP, SEXP delta_uSEXP, SEXP group_idSEXP, SEXP perturbTypeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type p(pSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type delta_u(delta_uSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type group_id(group_idSEXP);
    Rcpp::traits::input_parameter< int >::type perturbType(perturbTypeSEXP);
    rcpp_result_gen = Rcpp::wrap(mlogit_update(p, delta_u, group_id, perturbType));
    return rcpp_result_gen;
END_RCPP
}
// contribToCS_eval_inplace
Rcpp::IntegerVector contribToCS_eval_inplace(Rcpp::NumericMatrix mat, int densityCol, Rcpp::Nullable<Rcpp::CharacterVector> newColNames);
RcppExport SEXP _RSiena_contribToCS_eval_inplace(SEXP matSEXP, SEXP densityColSEXP, SEXP newColNamesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< int >::type densityCol(densityColSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::CharacterVector> >::type newColNames(newColNamesSEXP);
    rcpp_result_gen = Rcpp::wrap(contribToCS_eval_inplace(mat, densityCol, newColNames));
    return rcpp_result_gen;
END_RCPP
}
// softmax_jac_rcpp
Rcpp::NumericMatrix softmax_jac_rcpp(const Rcpp::NumericVector& changeProb, const Rcpp::NumericMatrix& contribMat, const Rcpp::IntegerVector& group_id);
RcppExport SEXP _RSiena_softmax_jac_rcpp(SEXP changeProbSEXP, SEXP contribMatSEXP, SEXP group_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type changeProb(changeProbSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type contribMat(contribMatSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type group_id(group_idSEXP);
    rcpp_result_gen = Rcpp::wrap(softmax_jac_rcpp(changeProb, contribMat, group_id));
    return rcpp_result_gen;
END_RCPP
}
// calculate_tie_prob_cpp
Rcpp::NumericVector calculate_tie_prob_cpp(Rcpp::NumericVector prob, Rcpp::NumericVector density);
RcppExport SEXP _RSiena_calculate_tie_prob_cpp(SEXP probSEXP, SEXP densitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type prob(probSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type density(densitySEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_tie_prob_cpp(prob, density));
    return rcpp_result_gen;
END_RCPP
}
