# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

softmax_arma <- function(x) {
    .Call(`_RSiena_softmax_arma`, x)
}

softmax_arma_by_group <- function(x, group) {
    .Call(`_RSiena_softmax_arma_by_group`, x, group)
}

