# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

softmax_rcpp_by_group <- function(x, group) {
    .Call(`_RSiena_softmax_rcpp_by_group`, x, group)
}

grouped_agg_cpp <- function(x, G, na_rm = TRUE, do_mean = TRUE) {
    .Call(`_RSiena_grouped_agg_cpp`, x, G, na_rm, do_mean)
}

build_scatter_idx <- function(G_sorted, ord) {
    .Call(`_RSiena_build_scatter_idx`, G_sorted, ord)
}

scatter_agg_1d <- function(vals, row_group, nGroups, na_rm = TRUE) {
    .Call(`_RSiena_scatter_agg_1d`, vals, row_group, nGroups, na_rm)
}

grouped_agg_matrix_cpp <- function(X, G, na_rm = TRUE, do_mean = FALSE) {
    .Call(`_RSiena_grouped_agg_matrix_cpp`, X, G, na_rm, do_mean)
}

grouped_agg_from_cols <- function(x, group_cols, na_rm = TRUE, do_mean = TRUE) {
    .Call(`_RSiena_grouped_agg_from_cols`, x, group_cols, na_rm, do_mean)
}

loo_change_probs <- function(contribMat, theta, group_id) {
    .Call(`_RSiena_loo_change_probs`, contribMat, theta, group_id)
}

l1d_grouped <- function(ref, loo, group_id) {
    .Call(`_RSiena_l1d_grouped`, ref, loo, group_id)
}

kld_grouped <- function(ref, loo, group_id) {
    .Call(`_RSiena_kld_grouped`, ref, loo, group_id)
}

mlogit_update <- function(p, delta_u, group_id, perturbType) {
    .Call(`_RSiena_mlogit_update`, p, delta_u, group_id, perturbType)
}

contribToCS_eval_inplace <- function(mat, densityCol, newColNames = NULL) {
    .Call(`_RSiena_contribToCS_eval_inplace`, mat, densityCol, newColNames)
}

softmax_jac_rcpp <- function(changeProb, contribMat, group_id) {
    .Call(`_RSiena_softmax_jac_rcpp`, changeProb, contribMat, group_id)
}

calculate_tie_prob_cpp <- function(prob, density) {
    .Call(`_RSiena_calculate_tie_prob_cpp`, prob, density)
}

